PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX expresses: <http://purl.obolibrary.org/obo/RO_0002292>
SELECT ?cell WHERE { VALUES ?marker { <http://identifiers.org/hgnc/6445> } ?cell expresses: ?marker . } 