PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050> PREFIX cell: <http://purl.obolibrary.org/obo/CL_0000000>
SELECT DISTINCT ?location WHERE { VALUES ?cell { <http://purl.obolibrary.org/obo/CL_4030022> <http://purl.obolibrary.org/obo/CL_1001318> <http://purl.obolibrary.org/obo/CL_1000768> } ?cell rdfs:subClassOf cell: . ?cell part_of: ?location }